services:

  user:
    image: nginx:1.21.1
    container_name: user
    volumes:
      - "./nginx/reverse_proxy_user.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 21004:80

  nginx:
    image: nginx:1.21.1
    container_name: nginx
    volumes:
      - "./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
    depends_on:
      - user
